CREATE SCHEMA IF NOT EXISTS ainoteapi;

CREATE TABLE IF NOT EXISTS ainoteapi.users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'AGENT'
);

CREATE TABLE IF NOT EXISTS ainoteapi.notes (
    id SERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES ainoteapi.users(id),
    rawtext TEXT NOT NULL,
    summary TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attempts INT NOT NULL DEFAULT 0
);
